# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9379ad8a59804927022d83f5bdaefbb622f0368b412fe0451efd8681f58fef8b6f881e13ed6c6cc809c945eec1a50dcba35c9ae74139c26905ab61917a3b8411

test:
  secret_key_base: 3a5039dd5366c1def800eadc7818f53da06d7a3cb9d1ac12545c1bd40e206414b5f410700e18e9de709ba4f6a3ed302e0a8eb9270d9ef4c94aabf345058b95fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
